### ISSUE TITLE
Baraja Dataset not accessible

### ISSUE THREAD

**Issue by DScheub** [darrenjkt/SEE-MTDA#4]
Hi, I'd like to try your repo but can't access the Gdrive with the Baraja dataset. Would you mind checking?

**Comment by darrenjkt** [comment]
Sorry about that, I've edited the download link here https://github.com/darrenjkt/SEE-MTDA/blob/main/docs/DATASET_PREPARATION.md

**Comment by DScheub** [comment]
Thank you
